on:
  push:
    branches:
      - master
      - develop

env:
  VERSION: ${{ github.sha }}
  IMAGE: ${{ format('gcr.io/indegser/sejong:{0}', github.sha) }}

name: Pipeline
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set edge env
        if: endsWith(github.ref, '/develop')
        run: |
          echo "::set-env name=CLUSTER::indegser-edge"
          echo "::set-env name=DATABASE_URL::${{ secrets.EDGE_DB }}"
      - name: Set prod env
        if: endsWith(github.ref, '/master')
        run: |
          echo "::set-env name=CLUSTER::indegser-prod"
          echo "::set-env name=DATABASE_URL::${{ secrets.PROD_DB }}"
      - uses: actions/checkout@v1
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: indegser
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - name: Docker
        run: |
          gcloud auth configure-docker
          docker build -t $IMAGE .
          docker push $IMAGE
      - name: Secret
        run: |
          gcloud container clusters get-credentials $CLUSTER --zone asia-northeast3-a
          ./deploy/update-secret.sh
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          AWS_ID: ${{ secrets.AWS_ID }}
          AWS_SECRET: ${{ secrets.AWS_SECRET }}
      - name: Deploy
        run: |
          ./deploy/update-tag.sh
          kubectl apply -k ./deploy
          kubectl get services -o wide
