on:
  push:
    branches:
      - master
      - develop

env:
  SHA: ${{ github.sha }}

name: Pipeline
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set edge env
        if: endsWith(github.ref, '/develop')
        run: |
          echo "::set-env name=PROJECT::indegser-edge"
          echo "::set-env name=GCP_SA_KEY::${{ secrets.GCP_EDGE_KEY }}"
          echo "::set-env name=DATABASE_URL::${{ secrets.EDGE_DB }}"
      - name: Set prod env
        if: endsWith(github.ref, '/master')
        run: |
          echo "::set-env name=PROJECT::indegser-prod"
          echo "::set-env name=GCP_SA_KEY::${{ secrets.GCP_PROD_KEY }}"
          echo "::set-env name=DATABASE_URL::${{ secrets.PROD_DB }}"
      - uses: actions/checkout@v1
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ env.PROJECT }}
          service_account_email: ${{ format('deploy@{0}.iam.gserviceaccount.com', env.PROJECT) }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - name: Deploy
        run: |
          gcloud app deploy --project $PROJECT
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          AWS_ID: ${{ secrets.AWS_ID }}
          AWS_SECRET: ${{ secrets.AWS_SECRET }}
