on:
  push:
    branches:
      - master
      - develop

name: Pipeline
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set edge env
        if: endsWith(github.ref, '/develop')
        run: |
          echo "::set-env name=PROJECT::indegser-edge"
          echo "::set-env name=PUBLISH_PROFILE::${{ secrets.EDGE_PUBLISH_PROFILE }}"
      - name: Set prod env
        if: endsWith(github.ref, '/master')
        run: |
          echo "::set-env name=PROJECT::indegser-prod"
          echo "::set-env name=PUBLISH_PROFILE::${{ secrets.PROD_PUBLISH_PROFILE }}"
      - name: Setup Node 10.x
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install and build
        run: |
          npm run build --if-present
      - name: Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.PROJECT }}
          publish-profile: ${{ env.PUBLISH_PROFILE }}
