on:
  push:
    branches:
      - master
      - develop

name: Docker push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set edge env
        if: endsWith(github.ref, '/develop')
        run: |
          echo "::set-env name=PROJECT::sejong-edge"
      - name: Set prod env
        if: endsWith(github.ref, '/master')
        run: |
          echo "::set-env name=PROJECT::sejong-prod"
      - name: Checkout
        uses: actions/checkout@v1
      - name: Deploy
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: indegser/${{ env.PROJECT }}
          tags: latest
