on:
  push:
    branches:
      - master

name: Production CI
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Install dependencies
        run: |
          npm install
      - name: Migrate
        run: |
          npx db-migrate up
        env:
          DATABASE_URL: ${{ secrets.PROD_DB }}
      - name: Deploy
        run: |
          npx now --prod --token $NOW_TOKEN --env DATABASE_URL=$DATABASE_URL --confirm
        env:
          NOW_TOKEN: ${{ secrets.NOW_TOKEN }}
          DATABASE_URL: ${{ secrets.PROD_DB }}
          NOW_ORG_ID: team_AAkK6ALVj9oOHZ6WuFS1i56y
          NOW_PROJECT_ID: ${{ secrets.PROD_PROJECT_ID }}
